# Generated by Django 5.2.9 on 2026-05-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='Thumbnail filename only, e.g. getting-started.jpg — file must be uploaded to the thumbnails directory on the server.', max_length=255),
        ),
    ]
