# Generated by Django 5.2.9 on 2026-05-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
