# Generated by Django 5.2.9 on 2026-05-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...). If set, the YouTube player and thumbnail are used automatically.', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='filename',
            field=models.CharField(blank=True, help_text='Filename only, e.g. getting-started.mp4 — file must be uploaded to the videos directory on the server. Leave blank if using a YouTube URL.', max_length=255),
        ),
    ]
