# Generated by Django 5.2.9 on 2026-05-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_alter_video_options_video_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
